# Generated by Django 3.2.4 on 2021-07-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210702_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updatesmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('new_update', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
