# Generated by Django 3.2.4 on 2021-07-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_updatesmodel_published_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Updatesmodel',
            new_name='UPDATE',
        ),
    ]
