# Generated by Django 3.2.4 on 2021-07-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_updatesmodel_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='published_date',
            field=models.DateTimeField(default='django.utils.timezone.now'),
        ),
    ]
